AP_PLAY = "assets/play.png"
AP_REPLAY = "assets/replay.png"
AP_RESET = "assets/reset.png"
AP_BACK = "assets/back.png"

ARRAY_LENGTH_MIN_LIMIT, ARRAY_LENGTH_MAX_LIMIT = 20, 200
ARRAY_MIN_VALUE, ARRAY_MAX_VALUE = 50, 400
SLIDER_DEFAULT_VALUE = 100
SCREEN_MIN_WIDTH_LIMIT, SCREEN_MIN_HEIGHT_LIMIT = 500,300
SCR_WIDTH, SCR_HEIGHT = 600, 500
RECT_COLOR = "red"
CANVAS_WIDTH, CANVAS_HEIGHT = 550, 400
ALGO_DELAY_MS = 50
